# Maps SYSTEM_ icon keys (from Airbnb's API) to human-readable display labels.
# Sourced from scanning outputs/02_details_scrape/mt_hood/property_details_*.json.
# Note: Airbnb icon keys are reused across amenities, house rules, and highlights —
# see notes below for dual-context icons.
SYSTEM_LABEL_MAP: dict[str, str] = {
    # ── Bathroom ──────────────────────────────────────────────────────────────
    "SYSTEM_BATHTUB": "Bathtub",
    "SYSTEM_HAIRDRYER": "Hair Dryer",
    "SYSTEM_SHAMPOO": "Shampoo / Conditioner",
    "SYSTEM_SOAP": "Body Soap",
    "SYSTEM_HOT_WATER": "Hot Water",
    "SYSTEM_TOILETRIES": "Essentials",
    "SYSTEM_SHOWER": "Outdoor Shower / Private Bathroom",
    "SYSTEM_TOILET_BIDET": "Bidet",
    # ── Bedroom & Sleep ───────────────────────────────────────────────────────
    "SYSTEM_BLANKETS": "Bed Linens",
    "SYSTEM_PILLOW": "Extra Pillows & Blankets",
    "SYSTEM_BLACKOUT_SHADES": "Room-Darkening Shades",
    "SYSTEM_WARDROBE": "Clothing Storage",
    # ── Kitchen & Dining ──────────────────────────────────────────────────────
    "SYSTEM_MINI_BAR": "Mini Fridge",
    "SYSTEM_MICROWAVE": "Microwave",
    "SYSTEM_DISHWASHER": "Dishwasher",
    "SYSTEM_STOVE": "Stove",
    "SYSTEM_OVEN": "Oven",
    "SYSTEM_TOASTER": "Toaster",
    "SYSTEM_BLENDER": "Blender",
    "SYSTEM_RICE_COOKER": "Rice Maker",
    "SYSTEM_BAKING_SHEET": "Baking Sheet / Bread Maker",
    "SYSTEM_WATER_KETTLE": "Hot Water Kettle",
    "SYSTEM_DISHES_AND_SILVERWARE": "Dishes & Silverware",
    "SYSTEM_DINING_TABLE": "Dining Table",
    "SYSTEM_CHILD_UTENSILS": "Children's Dinnerware",
    # ── Laundry & Cleaning ────────────────────────────────────────────────────
    "SYSTEM_IRON": "Iron",
    "SYSTEM_HANGERS": "Hangers / Drying Rack",
    "SYSTEM_WASHER": "Washer",
    "SYSTEM_DRYER": "Dryer",
    "SYSTEM_LAUNDRY_SERVICE": "Laundromat Nearby",
    "SYSTEM_CLEANING_SUPPLIES": "Cleaning Products",
    "SYSTEM_CLEAN": "Cleaning / Housekeeping Available",
    # ── Climate & Comfort ─────────────────────────────────────────────────────
    "SYSTEM_THERMOMETER": "Heating",
    "SYSTEM_SNOWFLAKE": "Air Conditioning",
    "SYSTEM_FAN_CEILING": "Ceiling Fan",
    "SYSTEM_FAN_PORTABLE": "Portable Fans",
    # ── Safety & Security ─────────────────────────────────────────────────────
    "SYSTEM_DETECTOR_CO": "Carbon Monoxide Alarm",
    "SYSTEM_FIRE_EXTINGUISHER": "Fire Extinguisher",
    "SYSTEM_FIRST_AID_KIT": "First Aid Kit",
    "SYSTEM_SURVEILLANCE": "Exterior Security Cameras on Property",
    "SYSTEM_SAFE": "Safe / Lockbox",
    "SYSTEM_FIREPLACE_GUARD": "Fireplace Guards",
    "SYSTEM_AV_VOLUME": "Noise Decibel Monitors",
    # ── Tech & Work ───────────────────────────────────────────────────────────
    "SYSTEM_WORKSPACE": "Dedicated Workspace",
    "SYSTEM_TV": "TV",
    "SYSTEM_CABLE": "Ethernet Connection",
    "SYSTEM_SPEAKERS": "Sound System",
    # ── Entertainment ─────────────────────────────────────────────────────────
    "SYSTEM_PING_PONG": "Ping Pong Table",
    "SYSTEM_ARCADE_MACHINE": "Arcade Games",
    "SYSTEM_CHESS": "Life Size Games",
    "SYSTEM_PIANO": "Piano",
    "SYSTEM_POOL_TABLE": "Pool Table",
    "SYSTEM_BOARD_GAMES": "Board Games",
    "SYSTEM_BOOK": "Books & Reading Material",
    "SYSTEM_RECORD_PLAYER": "Record Player",
    "SYSTEM_VIDEO_GAME": "Game Console",
    "SYSTEM_ANIME": "Theme Room",
    # ── Children & Family ─────────────────────────────────────────────────────
    "SYSTEM_CRIB": "Crib",
    "SYSTEM_PACK_N_PLAY": "Pack 'n Play / Travel Crib",
    "SYSTEM_OUTLET_COVER": "Outlet Covers",
    "SYSTEM_BABY_GATE": "Baby Safety Gates",
    "SYSTEM_HIGH_CHAIR": "High Chair",
    "SYSTEM_TOYS": "Children's Books & Toys / Playroom",
    "SYSTEM_PLAY_SLIDE": "Outdoor Playground",
    # ── Outdoor & Recreation ──────────────────────────────────────────────────
    "SYSTEM_PATIO_BALCONY": "Patio or Balcony",
    "SYSTEM_GRILL": "BBQ Grill",
    "SYSTEM_FIREPIT": "Fire Pit",
    "SYSTEM_FIREPLACE": "Indoor Fireplace",
    "SYSTEM_HAMMOCK": "Hammock",
    "SYSTEM_POOL": "Pool",
    "SYSTEM_JACUZZI": "Hot Tub",
    "SYSTEM_GYM": "Exercise Equipment / Gym",
    "SYSTEM_BEACH": "Beach Access",
    "SYSTEM_BIKE": "Bikes",
    "SYSTEM_SAUNA": "Sauna",
    "SYSTEM_SUN_DECK": "Sun Loungers",
    "SYSTEM_ROOFTOP_DECK": "Outdoor Furniture / Dining Area",
    # ── Views & Scenery ───────────────────────────────────────────────────────
    "SYSTEM_VIEW_MOUNTAIN": "Mountain / Valley View",
    "SYSTEM_VIEW_OCEAN": "Water View",
    "SYSTEM_LAKE": "Lake View",
    "SYSTEM_GOLF": "Golf Course View / Mini Golf",
    "SYSTEM_FLOWER": "Backyard / Garden View",
    # ── Access & Check-in ─────────────────────────────────────────────────────
    "SYSTEM_CHECK_IN": "Self Check-In",
    "SYSTEM_LOCK_ON_DOOR": "Smart Lock / Bedroom Door Lock",
    "SYSTEM_BUZZER": "Keypad",
    "SYSTEM_DOOR": "Private Entrance",
    "SYSTEM_LUGGAGE_DROP": "Luggage Drop-Off Allowed",
    "SYSTEM_NO_PRIVATE_ENTRANCE": "No Private Entrance",
    "SYSTEM_NO_STAIRS": "Single-Level Home (No Stairs)",
    "SYSTEM_EV_CHARGER": "EV Charger",
    # ── House Rules ───────────────────────────────────────────────────────────
    "SYSTEM_NO_EVENTS": "No Parties or Events",
    "SYSTEM_SMOKING_ALLOWED": "Smoking Allowed",
    "SYSTEM_PETS": "Pets Allowed",
    "SYSTEM_CAMERA": "Commercial Photography Allowed",
    # ── Checkout Instructions ─────────────────────────────────────────────────
    "SYSTEM_TOWEL": "Gather Used Towels",
    "SYSTEM_POWER_SWITCH": "Turn Things Off",
    "SYSTEM_LOCK": "Lock Up",
    "SYSTEM_HOST_OWNERS": "Return Keys / Host Greeting",
    "SYSTEM_TRASH": "Trash (Checkout Rule / Compactor)",
}
